
--MESURE Paris , jour ou il ya un pick NO2

SELECT
    STATION_ID,
    TRUNC(HORAIRE) as JOUR,
    MIN(NO2) as MIN_VAL,
    MAX(NO2) as MAX_VAL,
    MAX(NO2) - MIN(NO2) as ETENDUE,
    AVG(NO2) as AVG_VAL,
    STDDEV(NO2) as ECART_TYPE,
    VARIANCE(NO2) as VARIANCE,
    (STDDEV(NO2) / NULLIF(AVG(NO2), 0)) * 100 as COEFF_VARIATION_PCT,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY NO2) as Q1,
    MEDIAN(NO2) as MEDIAN_VAL,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY NO2) as Q3,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY NO2) -
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY NO2) as IQR
FROM MESURE_PARIS_PROPRE
WHERE (TRUNC(HORAIRE), STATION_ID) = (
    SELECT TRUNC(HORAIRE), STATION_ID
    FROM MESURE_PARIS_PROPRE
    WHERE NO2 = (SELECT MAX(NO2) FROM MESURE_PARIS_PROPRE)
    FETCH FIRST 1 ROW ONLY
)
GROUP BY STATION_ID, TRUNC(HORAIRE)

--MESURE VERSAILLES , jour ou il ya un pick NO2

SELECT
    STATION_ID,
    TRUNC(HORAIRE) as JOUR,
    MIN(NO2) as MIN_VAL,
    MAX(NO2) as MAX_VAL,
    MAX(NO2) - MIN(NO2) as ETENDUE,
    AVG(NO2) as AVG_VAL,
    STDDEV(NO2) as ECART_TYPE,
    VARIANCE(NO2) as VARIANCE,
    (STDDEV(NO2) / NULLIF(AVG(NO2), 0)) * 100 as COEFF_VARIATION_PCT,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY NO2) as Q1,
    MEDIAN(NO2) as MEDIAN_VAL,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY NO2) as Q3,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY NO2) -
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY NO2) as IQR
FROM MESURE_VERSAILLES_PROPRE
WHERE (TRUNC(HORAIRE), STATION_ID) = (
    SELECT TRUNC(HORAIRE), STATION_ID
    FROM MESURE_VERSAILLES_PROPRE
    WHERE NO2 = (SELECT MAX(NO2) FROM MESURE_VERSAILLES_PROPRE )
    FETCH FIRST 1 ROW ONLY
)
GROUP BY STATION_ID, TRUNC(HORAIRE)

--MESURE PEKIN , jour ou il ya un pick NO2

SELECT
    STATION_ID,
    TRUNC(HORAIRE) as JOUR,
    MIN(NO2) as MIN_VAL,
    MAX(NO2) as MAX_VAL,
    MAX(NO2) - MIN(NO2) as ETENDUE,
    AVG(NO2) as AVG_VAL,
    STDDEV(NO2) as ECART_TYPE,
    VARIANCE(NO2) as VARIANCE,
    (STDDEV(NO2) / NULLIF(AVG(NO2), 0)) * 100 as COEFF_VARIATION_PCT,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY NO2) as Q1,
    MEDIAN(NO2) as MEDIAN_VAL,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY NO2) as Q3,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY NO2) -
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY NO2) as IQR
FROM MESURE_PEKIN_STATION1002
WHERE (TRUNC(HORAIRE), STATION_ID) = (
    SELECT TRUNC(HORAIRE), STATION_ID
    FROM MESURE_PEKIN_STATION1002
    WHERE NO2 = (SELECT MAX(NO2) FROM MESURE_PEKIN_STATION1002 )
    FETCH FIRST 1 ROW ONLY
)
GROUP BY STATION_ID, TRUNC(HORAIRE)

--MESURE SHANGHAI , jour ou il ya un pick NO2

SELECT
    STATION_ID,
    TRUNC(HORAIRE) as JOUR,
    MIN(NO2) as MIN_VAL,
    MAX(NO2) as MAX_VAL,
    MAX(NO2) - MIN(NO2) as ETENDUE,
    AVG(NO2) as AVG_VAL,
    STDDEV(NO2) as ECART_TYPE,
    VARIANCE(NO2) as VARIANCE,
    (STDDEV(NO2) / NULLIF(AVG(NO2), 0)) * 100 as COEFF_VARIATION_PCT,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY NO2) as Q1,
    MEDIAN(NO2) as MEDIAN_VAL,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY NO2) as Q3,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY NO2) -
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY NO2) as IQR
FROM MESURE_SHANGHAI_STATION2001
WHERE (TRUNC(HORAIRE), STATION_ID) = (
    SELECT TRUNC(HORAIRE), STATION_ID
    FROM MESURE_SHANGHAI_STATION2001
    WHERE NO2 = (SELECT MAX(NO2) FROM MESURE_SHANGHAI_STATION2001 )
    FETCH FIRST 1 ROW ONLY
)
GROUP BY STATION_ID, TRUNC(HORAIRE)